### ISSUE TITLE
Demo.py的pyglet.gl.ContextException: Could not create GL context问题 与 预训练模型的可视化问题

### ISSUE THREAD

**Issue by 1192405754** [PantoMatrix/PantoMatrix#127]
首先是Demo.py的pyglet运行问题：
        在运行python scripts/EMAGE_2024/demo.py时，运行到subprocess_index=11 后报错：An error has been caught in function 'wrapper', process 'MainProcess' (31273), thread 'AnyIO worker thread' (140157717763840): multiprocessing .pool.RemoteTraceback: """
Traceback (most recent call last):
  File "/root/anaconda3/envs/emagepy38/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/anaconda3/envs/emagepy38/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/root/PantoMatrix/scripts/EMAGE_2024/utils/fast_render.py", line 157, in sub_process_process_frame_no_gt
    render_frames_and_enqueue(fids, frame_vertex_pairs, faces, render_video_width, render_video_height, fig_queue)
  File "/root/PantoMatrix/scripts/EMAGE_2024/utils/fast_render.py", line 111, in render_frames_and_enqueue
    renderer = pyrender.OffscreenRenderer(*fig_resolution)
  File "/root/anaconda3/envs/emagepy38/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/root/anaconda3/envs/emagepy38/lib/python3.8/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/root/anaconda3/envs/emagepy38/lib/python3.8/site-packages/pyrender/platforms/pyglet_platform.py", line 50, in init_context
    self._window = pyglet.window.Window(config=conf, visible=False,
  File "/root/anaconda3/envs/emagepy38/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 168, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/root/anaconda3/envs/emagepy38/lib/python3.8/site-packages/pyglet/window/__init__.py", line 573, in __init__
    context = config.create_context(gl.current_context)
  File "/root/anaconda3/envs/emagepy38/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 204, in create_context
    return XlibContextARB(self, share)
  File "/root/anaconda3/envs/emagepy38/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 314, in __init__
    super(XlibContext13, self).__init__(config, share)
  File "/root/anaconda3/envs/emagepy38/lib/python3.8/site-packages/pyglet/gl/xlib.py", line 218, in __init__
    raise gl.ContextException('Could not create GL context')
pyglet.gl.ContextException: Could not create GL context
"""
我在网上查找了相关pyglet.gl.ContextException: Could not create GL context的问题，我现在使用的OpenGL以及pyglet版本信息如下：
![image](https://github.com/PantoMatrix/PantoMatrix/assets/101398025/dff10473-9776-4313-9616-54361a9853ca)
![image](https://github.com/PantoMatrix/PantoMatrix/assets/101398025/301b7441-aa86-442a-97bc-e46ef1726f0c)

请问该如何解决？

第二是预训练模型的可视化问题：
在运行python scripts/EMAGE_2024/test.py --config ./scripts/EMAGE_2024/configs/emage.yaml 测试代码后，获得一系列npz文件，请问可以通过什么方法将这些序列可视化？

期待回答，非常感谢。

**Comment by 1192405754** [comment]
有关问题1的事宜已经得到了很好的解决，现在对于问题2我还想知道更多相关信息。

感谢回答。

**Comment by zzhat0706** [comment]
关于SMPLX的npz可视化，我们制作了一个[blender的Addon](https://drive.google.com/drive/folders/1ukbifhHc85qWTzspEgvAxCXwn9mK4ifr)，请配合blender使用并直接读入npz文件，即可在blender上查看可视化。

About SMPLX's npz visualization, please download our [blender add-on](https://drive.google.com/drive/folders/1ukbifhHc85qWTzspEgvAxCXwn9mK4ifr). Then you can put all SMPLX npz in this add-on to visualize the results in blender.

**Comment by 1192405754** [comment]
@zzhat0706 好的，我后续会在blender上继续研究相关工作。非常感谢你的帮助！

**Comment by Lynn0901** [comment]
@1192405754 您好我也遇到问题1一样的问题，您是如何解决的？是包的版本不匹配吗
